name: Feature request
description: Suggest an idea for this project
title: "Quick description of the feature"
labels: [enhancement]
body:
  - type: textarea
    attributes:
      label: Describe the feature
      description: A clear and concise description of what the problem is
      placeholder: |
        Ex. I'm always frustrated when [...]
    validations:
      required: true
  - type: textarea
    attributes:
        label: Describe the solution you'd like or your expectation
        description: A clear and concise description of what you want to happen
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context about the feature request here
    validations:
      required: false